[build]
  functions = "netlify/functions"

# Define which paths this should apply to
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.spotify.com https://www.google-analytics.com https://*.ingest.sentry.io/ https://stats.g.doubleclick.net; script-src 'self' 'unsafe-inline' https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com; frame-src 'self';"  
